const axios = require('axios');
const { Resend } = require('resend');

const resend = new Resend(process.env.RESEND_API_KEY);

async function sendEmail(to, subject, html, attachments = []) {
  const attachmentsFormatted = attachments.map(a => ({
    filename: a.filename,
    content: a.content.toString('base64'),
  }));

  const { data, error } = await resend.emails.send({
    from: 'Richards & Law <onboarding@resend.dev>',
    to: [to],
    subject: subject,
    html: html,
    attachments: attachmentsFormatted,
  });

  if (error) {
    console.error('❌ Resend Error:', error);
    throw error;
  }

  console.log(`✅ Email sent to ${to}:`, data?.id);
  return data;
}

// ── Verification email to paralegal ──────────────────────────────────────────
async function sendVerificationEmail(extractedData, verificationToken, matterId) {
  const verifyUrl = `${process.env.BASE_URL}/verify/${verificationToken}`;
  const accidentDateDisplay = extractedData.accidentDate || 'Unknown Date';
  const clientName = `${extractedData.clientFirstName} ${extractedData.clientLastName}`;
  const defendantName = extractedData.defendantName || 'Not found';

  const subject = `[ACTION REQUIRED] Verify Police Report — ${clientName} (${accidentDateDisplay})`;

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto; }
        .header { background: #1a3c5e; color: white; padding: 20px; border-radius: 8px 8px 0 0; }
        .content { background: #f9f9f9; padding: 24px; border: 1px solid #ddd; }
        .field-table { width: 100%; border-collapse: collapse; margin: 16px 0; }
        .field-table tr { border-bottom: 1px solid #eee; }
        .field-table td { padding: 10px 8px; }
        .field-table td:first-child { font-weight: bold; color: #555; width: 40%; }
        .field-table td:last-child { color: #111; }
        .warning { background: #fff3cd; border: 1px solid #ffc107; padding: 12px; border-radius: 4px; margin: 12px 0; font-size: 14px; }
        .footer { font-size: 12px; color: #888; padding: 16px; text-align: center; }
      </style>
    </head>
    <body>
      <div class="header">
        <h2 style="margin:0">📋 Police Report — Data Verification Required</h2>
        <p style="margin:4px 0 0; opacity:0.8;">Richards & Law Automation System</p>
      </div>
      <div class="content">
        <p>A police report PDF has been processed. Please review the extracted data below and confirm before it is written to Clio Manage.</p>
        <div class="warning">
          ⚠️ <strong>Action Required:</strong> This data has NOT been saved to Clio yet.
          Click the button below to review, edit if needed, and approve.
        </div>
        <h3 style="color:#1a3c5e;">Extracted Information</h3>
        <table class="field-table">
          <tr><td>Client Name</td><td>${clientName}</td></tr>
          <tr><td>Accident Date</td><td>${accidentDateDisplay}</td></tr>
          <tr><td>Accident Location</td><td>${extractedData.accidentLocation || 'Not found'}</td></tr>
          <tr><td>Defendant Name</td><td>${defendantName}</td></tr>
          <tr><td>Client Vehicle Plate</td><td>${extractedData.clientVehiclePlate || 'Not found'}</td></tr>
          <tr><td>No. Injured</td><td>${extractedData.numberOfInjured ?? 'Not found'}</td></tr>
          <tr><td>Report Number</td><td>${extractedData.accidentReportNumber || 'Not found'}</td></tr>
          <tr><td>Accident Description</td><td>${extractedData.accidentDescription || 'Not found'}</td></tr>
        </table>
        <p style="text-align:center;">
          <a href="${verifyUrl}"
             style="background:#1a3c5e; color:white; padding:14px 28px; text-decoration:none;
                    border-radius:6px; font-size:16px; font-weight:bold; display:inline-block; margin:20px 0;">
            Review &amp; Approve →
          </a>
        </p>
        <p style="margin-top:12px; font-size:13px; color:#666;">
          Or copy this link into your browser:<br/>
          <strong style="color:#1a3c5e; word-break:break-all;">${verifyUrl}</strong>
        </p>
        <p style="font-size:13px; color:#666;">This link expires in 24 hours. &nbsp;|&nbsp; Matter ID: ${matterId}</p>
      </div>
      <div class="footer">Richards &amp; Law Automation System — Internal Use Only</div>
    </body>
    </html>
  `;

  await sendEmail(process.env.PARALEGAL_EMAIL, subject, html);
  console.log('✅ Verification email sent');
}

// ── Personalized client email generated by Claude ────────────────────────────
async function generatePersonalizedEmail(firstName, extractedData, solDate, bookingLink) {
  const prompt = `You are a compassionate personal injury attorney writing a warm, personalized intake email to a new client.

Client first name: ${firstName}
Accident date: ${extractedData.accidentDate}
Accident location: ${extractedData.accidentLocation}
Accident description: ${extractedData.accidentDescription}
Defendant name: ${extractedData.defendantName}

Write a warm, human, professional email that:
1. Opens with genuine empathy about what happened to them
2. Briefly references their specific accident (date, location, what happened) in a compassionate way
3. Reassures them they are in good hands
4. Mentions the retainer agreement is attached for their review
5. Do NOT mention the statute of limitations date
6. Says they can book a consultation using the button below
7. Closes warmly

Format as clean HTML with inline styles.
The firm is Richards & Law, New York Personal Injury Attorneys.
Do NOT include a subject line.
Return only the email body HTML starting with <p>Dear ${firstName},</p>`;

  const response = await axios.post(
    'https://api.anthropic.com/v1/messages',
    {
      model: 'claude-sonnet-4-20250514',
      max_tokens: 1000,
      messages: [{ role: 'user', content: prompt }],
    },
    {
      headers: {
        'x-api-key': process.env.ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01',
        'content-type': 'application/json',
      },
    }
  );

  const generatedBody = response.data.content[0].text.trim();

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Georgia, serif; color: #333; max-width: 600px; margin: 0 auto; }
        .header { background: #1a3c5e; color: white; padding: 24px; border-radius: 8px 8px 0 0; }
        .content { background: #ffffff; padding: 28px; border: 1px solid #ddd; line-height: 1.7; font-size: 15px; }
        .footer { font-size: 12px; color: #888; padding: 16px; text-align: center; border-top: 1px solid #eee; }
      </style>
    </head>
    <body>
      <div class="header">
        <h2 style="margin:0; font-size:20px;">⚖️ Richards & Law</h2>
        <p style="margin:6px 0 0; opacity:0.85; font-size:13px;">New York Personal Injury Attorneys</p>
      </div>
      <div class="content">
        ${generatedBody}
        <div style="background:#fff3cd; border:1px solid #ffc107; padding:14px 18px; border-radius:6px; margin:24px 0; font-size:14px;">
          ⚠️ <strong>Important Legal Deadline:</strong> The Statute of Limitations for your claim is <strong>${solDate}</strong>. We must file before this date or your claim will be barred.
        </div>
        <div style="text-align:center; margin:28px 0 16px;">
          <a href="${bookingLink}"
             style="background:#1a3c5e; color:white; padding:14px 28px; text-decoration:none;
                    border-radius:6px; font-weight:bold; font-size:15px; display:inline-block;">
            📅 Book Your Consultation
          </a>
        </div>
      </div>
      <div class="footer">
        Richards &amp; Law — 123 Broadway, New York, NY 10006 — (212) 555-0100
      </div>
    </body>
    </html>
  `;
}

// ── Client email with retainer attached ──────────────────────────────────────
async function sendClientEmail(clientEmail, clientName, extractedData, solDate, bookingLink, matterId, retainerAttachment) {
  const firstName = clientName.split(' ')[0];
  const emailContent = await generatePersonalizedEmail(firstName, extractedData, solDate, bookingLink);

  const attachments = retainerAttachment ? [{
    filename: retainerAttachment.filename,
    content: retainerAttachment.buffer,
  }] : [];

  if (retainerAttachment) {
    console.log('📎 Attaching retainer:', retainerAttachment.filename);
  }

  await sendEmail(
    clientEmail,
    `Your Legal Representation — Richards & Law`,
    emailContent,
    attachments
  );
  console.log('✅ Client email sent');
}

module.exports = { sendVerificationEmail, sendClientEmail };